### ISSUE TITLE
Remove setcap and use alternative methods

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#31]
I haven't looked into this much, but it seems using setcap is frowned upon. We should evaluate the possible alternatives: https://github.com/mholt/caddy/issues/528#issuecomment-261125303

**Comment by mikelococo** [comment]
Did a little bit of reading about the systemd stuff. It looks in some sense like it's as simple as uncommenting these three lines: https://github.com/antoiner77/caddy-ansible/blob/82b59994ca0ce16e2596a663c43026113b681326/templates/caddy.service#L47-L49

The sticky part is appears to be that they only work in systemd v229 or later, which means:
- Ubuntu 16.04 is ok (includes that version of systemd.
- Fedora 25 is ok (ships systemd v231 per https://apps.fedoraproject.org/packages/systemd)
- RHEL/Cent 7 is not ok (ships systemd v219 per http://mirror.centos.org/centos/7/os/x86_64/Packages/)
- Debian Jessie is not ok (ships systemd v215 per https://packages.debian.org/jessie/systemd)

And of course the fact that systemd doesn't provide a solution for Upstart/Sysv users. That might mean a second option in addition to setcap, a series of platform checks, or more directly a systemd versoin check.

I didn't look into capsh, but presumably it's more likely to work consistently across all supported platforms.

**Comment by lbischof** [comment]
@mikelococo Thanks very much for looking into this issue. I think a version check would be ok and then just use systemd instead of setcap if the option is enabled. I currently don't have any time to implement it, though pull request are welcome

**Comment by mikelococo** [comment]
I had a look at capsh this evening and the mechanics are quite simple, though it's not super well documented. After poking around, it appears that we'd need to:

* Change the existing setcap invocation to (+ei instead of +ep in order to allow that capability to be inherited rather than granting it to the binary outright): `command: setcap cap_net_bind_service=+ei {{ caddy_bin|quote }}`
* Change the various initscripts to wrap the caddy exec in something like `sudo capsh --inh="cap_net_bind_service=" --user=mike -- -c "./caddy -conf caddyfile"` This instructs setsh to invoke caddy as the mike user and to give it place cap_net_bind_service capability in it's inheritable set.

By *both* marking the file as cap_net_bind_service inheritable, *and* inheriting that capability on invocation, caddy will get the ability to bind to low ports only when invoked via the root-requiring service scripts and won't be invokable by any user with shell access. This approach is (I think) more general than the systemd approach and should work on all the platforms where the current setcap scheme works.

I took a crack a a PR for the capsh approach, but I'm a little nervous about the init-script modifications. They all currently invoke caddy as the caddy user, whereas in the capsh scheme it must be invoked as root and capsh exec it as the caddy user. That seemed like a big change for a driveby PR.

So the options here seem to be:
* Let systemd bind the low-numbered port. Easy to implement, but only works on systemd.
* Modify how privileges are dropped in init scripts in order to make capsh work, which works everywhere but is more invasive.
* Or keep the status quo which is simple but gives non-root users the ability to abuse the caddy binary to snatch up low-numbers ports (which for most users of this playbook, is probably fine... how many people are using this playbook to host caddy servers on boxes where they give shells to untrusted users?)

cc @wmark, your comment in mholt/caddy528 was invaluable in researching options here. I'd be interested if you have any thoughts. I'm disinclined to go tearing up the init-scripts here, though we could do something if upstream supported capsh operation. Improving the situation for systemd boxes seems straightforward and worthwhile, though.

**Comment by SuperQ** [comment]
In doing some testing with Debian Stretch, it seems the behavior of systemd 232 refuses to allow the setcap to work without setting `AmbientCapabilities=CAP_NET_BIND_SERVICE`.  Or I'm just losing my mind.  It would be nice to be able to enable this via a flag.

There's also a nice trick to improve the use of setcap:

```
ExecStartPre=/sbin/setcap 'cap_net_bind_service=+iep' {{ caddy_bin_dir }}/caddy
```

I can file a PR to do these two things.

**Comment by lbischof** [comment]
@SuperQ If Systemd breaks the current setcap behavior and that setting is backwards compatible then we should add that.

What improves if we move setcap into the systemd service file? shouldn't this only be needed once (not at every start)? I see you added `i`, what does that change? I think we should probably leave setcap in the tasks because then we don't have to change every service file to include it (not only systemd)

**Comment by SuperQ** [comment]
Yea, I still haven't traced down exactly what changed in systemd's default security policy in Stretch that is causing normal setcap to not work without the additional settings.

Moving the setcap into the script avoids having another ansible setup step.

Oh, the `i` thing came from one of the various linked bugs I saw.  It's possibly not necessary, I was somewhat grasping for random changes trying to figure out why it wasn't working with the current deploy code.

**Comment by LorenzBischof** [comment]
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.

**Comment by SuperQ** [comment]
Thanks for the heads up! Glad someone is picking up maintenance of this code.

**Comment by mark-kubacki** [comment]
I did wonder why I'm pinged about this. CC me on the new issue or PR and I'll take a look.

This is no endorsement of *Caddyserver.*
